### ISSUE TITLE
Patch for bundled ell

### ISSUE THREAD

**Issue by vaukai** [dylanaraps/eiwd#1]
The bundled ell needs this upstream patch:
 https://git.kernel.org/pub/scm/libs/ell/ell.git/commit/?id=baae402095502376b4cd170867217abd4134c661 

Without that patch it doesn't compile.

**Comment by dylanaraps** [comment]
Thanks for reporting. I'll push a new tarball shortly.

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/eiwd/releases/tag/1.5-5
