### ISSUE TITLE
Upstreaming the patch?

### ISSUE THREAD

**Issue by tleydxdy** [dylanaraps/eiwd#9]
Was there any attempts to getting the patch upstreamed? If it where just macros I think it won't be that controversial. I had a little bit of a search on the mailing list and couldn't find any.

**Comment by dylanaraps** [comment]
Understandably, it's not something they are interested in. 

A maintained version of eiwd can be found here: https://github.com/illiliti/eiwd

**Comment by tleydxdy** [comment]
was there any known attempts?
